#!/bin/bash
# SPDX-FileCopyrightText: 2026 abirkel <abirkel@users.noreply.github.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# PlasmaZones Local Installer
# Installs the application to ~/.local (or custom prefix) without root privileges.

set -e

# Default install prefix
PREFIX="$HOME/.local"
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check for 'usr' directory in the distributed tarball structure
if [ -d "$SOURCE_DIR/usr" ]; then
    DIST_ROOT="$SOURCE_DIR/usr"
else
    echo "Error: Could not find 'usr' directory in $SOURCE_DIR."
    echo "This script is intended to be run from the extracted portable tarball."
    exit 1
fi

# Detect lib directory name (Fedora uses lib64, Debian/Arch use lib)
if [ -d "$DIST_ROOT/lib64" ]; then
    LIBDIR="lib64"
elif [ -d "$DIST_ROOT/lib" ]; then
    LIBDIR="lib"
else
    echo "Error: Could not find lib or lib64 directory in tarball."
    exit 1
fi

# Extract version from tarball directory name or VERSION file
VERSION="unknown"
if [ -f "$SOURCE_DIR/VERSION" ]; then
    VERSION=$(cat "$SOURCE_DIR/VERSION")
else
    # Try to extract from parent directory name (e.g., plasmazones-1.7.0-linux-x86_64)
    PARENT_DIR=$(basename "$(dirname "$SOURCE_DIR")")
    if [[ "$PARENT_DIR" =~ plasmazones-([0-9]+\.[0-9]+\.[0-9]+) ]]; then
        VERSION="${BASH_REMATCH[1]}"
    fi
fi

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)
        PREFIX="$2"
        shift 2
        ;;
        --help)
        echo "Usage: ./install.sh [--prefix PATH]"
        echo "Default prefix: $HOME/.local"
        exit 0
        ;;
        *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

MANIFEST_FILE="$PREFIX/share/plasmazones/install_manifest.txt"
NEED_RESTART=false

# Check for existing installation
if [ -f "$MANIFEST_FILE" ]; then
    # Read old version from manifest (first line: # version: X.Y.Z)
    OLD_VERSION=$(head -n 1 "$MANIFEST_FILE" | sed -n 's/^# version: //p')
    if [ -n "$OLD_VERSION" ]; then
        echo "Existing installation detected: v$OLD_VERSION"
        echo "Upgrading to v$VERSION..."
    else
        echo "Existing installation detected (version unknown)"
        echo "Upgrading to v$VERSION..."
    fi

    # Stop service before upgrade
    if systemctl --user is-active --quiet plasmazones.service 2>/dev/null; then
        echo "Stopping plasmazones service..."
        systemctl --user stop plasmazones.service
        NEED_RESTART=true
    fi
else
    echo "Installing PlasmaZones v$VERSION to $PREFIX..."
fi

# 1. Copy files (use -rT to merge into prefix, including hidden files)
echo "Copying files..."
mkdir -p "$PREFIX"
cp -rT "$DIST_ROOT" "$PREFIX/"

# 2. Generate manifest with version header
echo "Generating installation manifest..."
mkdir -p "$PREFIX/share/plasmazones"
{
    echo "# version: $VERSION"
    echo "# installed: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    ( cd "$DIST_ROOT" && find . -type d | sed 's|^\./||' | sed 's|^|DIR: |' )
    ( cd "$DIST_ROOT" && find . \( -type f -o -type l \) | sed 's|^\./||' )
} > "$MANIFEST_FILE"

# 3. Patch systemd service and install to user config directory
SERVICE_SRC="$PREFIX/lib/systemd/user/plasmazones.service"
SERVICE_DEST="$HOME/.config/systemd/user/plasmazones.service"

if [ -f "$SERVICE_SRC" ]; then
    echo "Installing systemd user service..."
    mkdir -p "$HOME/.config/systemd/user"
    cp "$SERVICE_SRC" "$SERVICE_DEST"
    # Patch the service file to use the correct binary path and add library path
    sed -i "s|ExecStart=/usr/bin/plasmazonesd|ExecStart=$PREFIX/bin/plasmazonesd|g" "$SERVICE_DEST"
    # Add LD_LIBRARY_PATH environment variable after [Service] line
    sed -i "/^\[Service\]/a Environment=\"LD_LIBRARY_PATH=$PREFIX/$LIBDIR\"" "$SERVICE_DEST"
else
    echo "Warning: Service file not found at $SERVICE_SRC"
fi

# 4. Setup environment variables for KDE session
ENV_FILE="$HOME/.config/environment.d/10-plasmazones.conf"
echo "Setting up session environment variables..."
mkdir -p "$HOME/.config/environment.d"

cat > "$ENV_FILE" << EOF
# PlasmaZones Environment Variables
# Generated by PlasmaZones installer v$VERSION
PATH=$PREFIX/bin:\${PATH}
QT_PLUGIN_PATH=$PREFIX/$LIBDIR/qt6/plugins:\${QT_PLUGIN_PATH}
QML2_IMPORT_PATH=$PREFIX/$LIBDIR/qt6/qml:\${QML2_IMPORT_PATH}
XDG_DATA_DIRS=$PREFIX/share:\${XDG_DATA_DIRS}
LD_LIBRARY_PATH=$PREFIX/$LIBDIR:\${LD_LIBRARY_PATH}
EOF

chmod 644 "$ENV_FILE"
echo "Environment configuration created at $ENV_FILE"

# 5. Export environment for the current session so kbuildsycoca6 and
#    verification steps can find the newly installed files.
export PATH="$PREFIX/bin:$PATH"
export QT_PLUGIN_PATH="$PREFIX/$LIBDIR/qt6/plugins:${QT_PLUGIN_PATH}"
export QML2_IMPORT_PATH="$PREFIX/$LIBDIR/qt6/qml:${QML2_IMPORT_PATH}"
export XDG_DATA_DIRS="$PREFIX/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export LD_LIBRARY_PATH="$PREFIX/$LIBDIR:${LD_LIBRARY_PATH}"

# 6. Refresh KDE service cache (with environment set so it finds our .desktop)
if command -v kbuildsycoca6 >/dev/null 2>&1; then
    echo "Refreshing KDE service cache..."
    kbuildsycoca6 --noincremental 2>/dev/null || true
fi

# Notify kded6 to rescan for new services
dbus-send --session --dest=org.kde.kded6 \
    /kded org.kde.kded6.reconfigure 2>/dev/null || true

# 7. Enable/restart service
if command -v systemctl >/dev/null 2>&1; then
    echo "Reloading systemd user daemon..."
    systemctl --user daemon-reload

    if [ "$NEED_RESTART" = true ]; then
        echo "Restarting plasmazones.service..."
        systemctl --user start plasmazones.service
    else
        echo "Enabling and starting plasmazones.service..."
        systemctl --user enable --now plasmazones.service
    fi
else
    echo "Warning: 'systemctl' not found. You may need to start the daemon manually."
fi

# 8. Verify KCM is discoverable
if command -v kcmshell6 >/dev/null 2>&1; then
    if kcmshell6 --list 2>/dev/null | grep -q kcm_plasmazones; then
        echo "KCM verified: kcm_plasmazones is discoverable."
    else
        echo ""
        echo "Note: KCM module not yet visible to System Settings in this session."
        echo "This is expected — it will appear after you log out and back in."
    fi
fi

echo ""
echo "============================================"
echo "Installation complete!"
echo "============================================"
echo ""
echo "IMPORTANT: You must LOG OUT and LOG BACK IN for PlasmaZones to work correctly."
echo "This is required for the environment variables to take effect in all applications."
echo ""
echo "After logging back in:"
echo "  - PlasmaZones will appear in System Settings"
echo "  - The daemon will start automatically"
echo "  - All features will be available"
echo ""
echo "To uninstall, run: $PREFIX/share/plasmazones/uninstall.sh"
