// SPDX-FileCopyrightText: 2026 fuddlesworth
// SPDX-License-Identifier: GPL-3.0-or-later

#include "ScriptedAlgorithmJsBuiltins.h"
#include <QString>

namespace PlasmaZones {
namespace ScriptedHelpers {

QString distributeWithGapsJs()
{
    return QStringLiteral(
        "function distributeWithGaps(total, count, gap) {"
        "  if (count <= 0 || total <= 0) return [];"
        "  if (count === 1) return [total];"
        "  var totalGaps = (count - 1) * gap;"
        "  var available = Math.max(count, total - totalGaps);"
        "  var base = Math.floor(available / count);"
        "  var remainder = available % count;"
        "  var sizes = [];"
        "  for (var i = 0; i < count; i++) {"
        "    var s = base;"
        "    if (remainder > 0) { s++; remainder--; }"
        "    sizes.push(s);"
        "  }"
        "  return sizes;"
        "}");
}

QString distributeWithMinSizesJs()
{
    return QStringLiteral(
        "function distributeWithMinSizes(total, count, gap, minDims) {"
        "  if (count <= 0 || total <= 0) return [];"
        "  if (count === 1) return [total];"
        "  var totalGaps = (count - 1) * gap;"
        "  var available = Math.max(count, total - totalGaps);"
        "  if (!minDims || minDims.length === 0) {"
        "    return distributeWithGaps(total, count, gap);"
        "  }"
        "  var mins = []; var totalMin = 0;"
        "  for (var i = 0; i < count; i++) {"
        "    var m = (i < minDims.length && minDims[i] > 0) ? minDims[i] : 1;"
        "    mins.push(m); totalMin += m;"
        "  }"
        "  var sizes = new Array(count);"
        "  if (totalMin >= available) {"
        "    var remaining = available; var remainingMin = totalMin;"
        "    for (var i = 0; i < count; i++) {"
        "      var allocated;"
        "      if (remainingMin > 0) {"
        "        allocated = Math.floor(remaining * mins[i] / remainingMin);"
        "      } else {"
        "        allocated = Math.floor(remaining / Math.max(1, count - i));"
        "      }"
        "      allocated = Math.max(1, Math.min(allocated, remaining));"
        "      sizes[i] = allocated;"
        "      remaining -= allocated; remainingMin -= mins[i];"
        "    }"
        "  } else {"
        "    var base = Math.floor(available / count);"
        "    var rem = available % count;"
        "    var equalSizes = [];"
        "    for (var i = 0; i < count; i++) {"
        "      var s = base; if (rem > 0) { s++; rem--; } equalSizes.push(s);"
        "    }"
        "    var equalSatisfies = true;"
        "    for (var i = 0; i < count; i++) {"
        "      if (equalSizes[i] < mins[i]) { equalSatisfies = false; break; }"
        "    }"
        "    if (equalSatisfies) {"
        "      sizes = equalSizes;"
        "    } else {"
        "      var equalShare = Math.floor(available / count);"
        "      var surplus = available - totalMin;"
        "      var unconstrainedCount = 0;"
        "      for (var i = 0; i < count; i++) {"
        "        sizes[i] = mins[i];"
        "        if (mins[i] <= equalShare) unconstrainedCount++;"
        "      }"
        "      if (unconstrainedCount > 0 && surplus > 0) {"
        "        var sBase = Math.floor(surplus / unconstrainedCount);"
        "        var sRem = surplus % unconstrainedCount;"
        "        for (var i = 0; i < count; i++) {"
        "          if (mins[i] <= equalShare) {"
        "            sizes[i] += sBase;"
        "            if (sRem > 0) { sizes[i]++; sRem--; }"
        "          }"
        "        }"
        "      } else if (surplus > 0) {"
        "        var sBase = Math.floor(surplus / count);"
        "        var sRem = surplus % count;"
        "        for (var i = 0; i < count; i++) {"
        "          sizes[i] += sBase;"
        "          if (sRem > 0) { sizes[i]++; sRem--; }"
        "        }"
        "      }"
        "    }"
        "  }"
        "  return sizes;"
        "}");
}

QString solveTwoPartJs()
{
    return QStringLiteral(
        "function solveTwoPart(contentDim, firstDim, secondDim, minFirst, minSecond) {"
        "  var totalMin = Math.max(minFirst, 0) + Math.max(minSecond, 0);"
        "  if (totalMin > contentDim && totalMin > 0) {"
        "    firstDim = Math.floor(contentDim * Math.max(minFirst, 1) / totalMin);"
        "    secondDim = contentDim - firstDim;"
        "  } else {"
        "    if (minFirst > 0 && firstDim < minFirst) {"
        "      firstDim = minFirst; secondDim = contentDim - firstDim;"
        "    }"
        "    if (minSecond > 0 && secondDim < minSecond) {"
        "      secondDim = minSecond; firstDim = contentDim - secondDim;"
        "    }"
        "  }"
        "  firstDim = Math.max(0, firstDim);"
        "  secondDim = Math.max(0, secondDim);"
        "  return {first: firstDim, second: secondDim};"
        "}");
}

QString solveThreeColumnJs()
{
    return QStringLiteral(
        "function solveThreeColumn(areaX, contentWidth, innerGap, splitRatio, minL, minC, minR) {"
        "  if (contentWidth <= 0) {"
        "    return {leftWidth:1, centerWidth:1, rightWidth:1, leftX:areaX, centerX:areaX, rightX:areaX};"
        "  }"
        "  var effMinLeft = Math.max(PZ_MIN_ZONE_SIZE, minL);"
        "  var effMinRight = Math.max(PZ_MIN_ZONE_SIZE, minR);"
        "  var maxCenter = Math.min(PZ_MAX_SPLIT,"
        "    1.0 - (effMinLeft + effMinRight) / contentWidth);"
        "  var centerRatio = Math.min(Math.max(splitRatio, PZ_MIN_SPLIT), Math.max(PZ_MIN_SPLIT, maxCenter));"
        "  if (minC > 0) {"
        "    var minCenterRatio = minC / contentWidth;"
        "    centerRatio = Math.max(centerRatio, Math.min(minCenterRatio, maxCenter));"
        "  }"
        "  var sideRatio = (1.0 - centerRatio) / 2.0;"
        "  var leftWidth = Math.floor(contentWidth * sideRatio);"
        "  var centerWidth = Math.floor(contentWidth * centerRatio);"
        "  var rightWidth = contentWidth - leftWidth - centerWidth;"
        "  var totalColumnMin = Math.max(minL, 0) + Math.max(minC, 0) + Math.max(minR, 0);"
        "  if (totalColumnMin > contentWidth && totalColumnMin > 0) {"
        "    var eL = Math.max(minL, 1); var eC = Math.max(minC, 1); var eR = Math.max(minR, 1);"
        "    var eT = eL + eC + eR;"
        "    leftWidth = Math.floor(contentWidth * eL / eT);"
        "    centerWidth = Math.floor(contentWidth * eC / eT);"
        "    rightWidth = contentWidth - leftWidth - centerWidth;"
        "  } else {"
        "    if (minL > 0 && leftWidth < minL) {"
        "      var deficit = minL - leftWidth; leftWidth = minL;"
        "      var fromCenter = Math.max(0, Math.min(deficit, centerWidth - Math.max(minC, 1)));"
        "      centerWidth -= fromCenter; rightWidth = contentWidth - leftWidth - centerWidth;"
        "    }"
        "    if (minR > 0 && rightWidth < minR) {"
        "      var deficit = minR - rightWidth; rightWidth = minR;"
        "      var fromCenter = Math.max(0, Math.min(deficit, centerWidth - Math.max(minC, 1)));"
        "      centerWidth -= fromCenter; leftWidth = contentWidth - rightWidth - centerWidth;"
        "    }"
        "    if (minC > 0 && centerWidth < minC) {"
        "      var deficit = minC - centerWidth; centerWidth = minC;"
        "      if (leftWidth >= rightWidth) {"
        "        var take = Math.min(deficit, leftWidth - 1);"
        "        leftWidth -= take; deficit -= take;"
        "        if (deficit > 0) rightWidth -= deficit;"
        "      } else {"
        "        var take = Math.min(deficit, rightWidth - 1);"
        "        rightWidth -= take; deficit -= take;"
        "        if (deficit > 0) leftWidth -= deficit;"
        "      }"
        "    }"
        "  }"
        "  leftWidth = Math.max(1, leftWidth);"
        "  centerWidth = Math.max(1, centerWidth);"
        "  rightWidth = Math.max(1, rightWidth);"
        "  var colSum = leftWidth + centerWidth + rightWidth;"
        "  if (colSum > contentWidth) {"
        "    var excess = colSum - contentWidth;"
        "    if (centerWidth >= leftWidth && centerWidth >= rightWidth) {"
        "      centerWidth = Math.max(1, centerWidth - excess);"
        "    } else if (leftWidth >= rightWidth) {"
        "      leftWidth = Math.max(1, leftWidth - excess);"
        "    } else {"
        "      rightWidth = Math.max(1, rightWidth - excess);"
        "    }"
        "  }"
        "  return {leftWidth: leftWidth, centerWidth: centerWidth, rightWidth: rightWidth,"
        "    leftX: areaX, centerX: areaX + leftWidth + innerGap,"
        "    rightX: areaX + leftWidth + innerGap + centerWidth + innerGap};"
        "}");
}

QString cumulativeMinDimsJs()
{
    return QStringLiteral(
        "function computeCumulativeMinDims(windowCount, minSizes, innerGap) {"
        "  var minW = new Array(windowCount + 1);"
        "  var minH = new Array(windowCount + 1);"
        "  for (var i = 0; i <= windowCount; i++) { minW[i] = 0; minH[i] = 0; }"
        "  if (!minSizes || minSizes.length === 0) return {minW: minW, minH: minH};"
        "  for (var i = windowCount - 1; i >= 0; i--) {"
        "    var mw = (i < minSizes.length && minSizes[i].w > 0) ? minSizes[i].w : 0;"
        "    var mh = (i < minSizes.length && minSizes[i].h > 0) ? minSizes[i].h : 0;"
        "    var splitV = (i % 2 === 0);"
        "    if (splitV) {"
        "      minW[i] = mw + ((i < windowCount - 1 && minW[i+1] > 0) ? innerGap + minW[i+1] : 0);"
        "      minH[i] = Math.max(mh, minH[i+1]);"
        "    } else {"
        "      minH[i] = mh + ((i < windowCount - 1 && minH[i+1] > 0) ? innerGap + minH[i+1] : 0);"
        "      minW[i] = Math.max(mw, minW[i+1]);"
        "    }"
        "  }"
        "  return {minW: minW, minH: minH};"
        "}");
}

QString gracefulDegradationJs()
{
    return QStringLiteral(
        "function appendGracefulDegradation(zones, remaining, leftover, innerGap) {"
        "  if (leftover <= 0) return;"
        "  if (remaining.width >= remaining.height) {"
        "    var maxFit = Math.max(1, Math.floor(remaining.width / PZ_MIN_ZONE_SIZE));"
        "    var fitCount = Math.min(leftover + 1, maxFit);"
        "    var widths = distributeWithGaps(remaining.width, fitCount, innerGap);"
        "    zones[zones.length - 1] = {x: remaining.x, y: remaining.y,"
        "      width: widths[0], height: remaining.height};"
        "    var cx = remaining.x + widths[0] + innerGap;"
        "    for (var j = 1; j < fitCount; j++) {"
        "      zones.push({x: cx, y: remaining.y, width: widths[j], height: remaining.height});"
        "      cx += widths[j] + innerGap;"
        "    }"
        "    for (var j = fitCount; j <= leftover; j++) {"
        "      zones.push({x: zones[zones.length-1].x, y: zones[zones.length-1].y,"
        "        width: zones[zones.length-1].width, height: zones[zones.length-1].height});"
        "    }"
        "  } else {"
        "    var maxFit = Math.max(1, Math.floor(remaining.height / PZ_MIN_ZONE_SIZE));"
        "    var fitCount = Math.min(leftover + 1, maxFit);"
        "    var heights = distributeWithGaps(remaining.height, fitCount, innerGap);"
        "    zones[zones.length - 1] = {x: remaining.x, y: remaining.y,"
        "      width: remaining.width, height: heights[0]};"
        "    var cy = remaining.y + heights[0] + innerGap;"
        "    for (var j = 1; j < fitCount; j++) {"
        "      zones.push({x: remaining.x, y: cy, width: remaining.width, height: heights[j]});"
        "      cy += heights[j] + innerGap;"
        "    }"
        "    for (var j = fitCount; j <= leftover; j++) {"
        "      zones.push({x: zones[zones.length-1].x, y: zones[zones.length-1].y,"
        "        width: zones[zones.length-1].width, height: zones[zones.length-1].height});"
        "    }"
        "  }"
        "}");
}

QString dwindleLayoutJs()
{
    return QStringLiteral(
        "function dwindleLayout(area, count, splitRatio, innerGap, minSizes) {"
        "  splitRatio = Math.min(Math.max(splitRatio, PZ_MIN_SPLIT), PZ_MAX_SPLIT);"
        "  var cumMinDims = computeCumulativeMinDims(count, minSizes, innerGap);"
        "  var remainingMinW = cumMinDims.minW;"
        "  var remainingMinH = cumMinDims.minH;"
        "  var remaining = {x: area.x, y: area.y, width: area.width, height: area.height};"
        "  var splitVertical = true;"
        "  var zones = [];"
        "  for (var i = 0; i < count; i++) {"
        "    if (i === count - 1 || remaining.width < PZ_MIN_ZONE_SIZE"
        "        || remaining.height < PZ_MIN_ZONE_SIZE"
        "        || (splitVertical && remaining.width <= innerGap)"
        "        || (!splitVertical && remaining.height <= innerGap)) {"
        "      zones.push({x: remaining.x, y: remaining.y,"
        "        width: remaining.width, height: remaining.height});"
        "      appendGracefulDegradation(zones, remaining, count - i - 1, innerGap);"
        "      break;"
        "    } else {"
        "      if (splitVertical) {"
        "        var contentWidth = remaining.width - innerGap;"
        "        var windowWidth = Math.floor(contentWidth * splitRatio);"
        "        if (minSizes && minSizes.length > 0 && i < minSizes.length"
        "            && minSizes[i].w > 0) {"
        "          windowWidth = Math.max(windowWidth, minSizes[i].w);"
        "        }"
        "        if (minSizes && minSizes.length > 0 && remainingMinW[i + 1] > 0) {"
        "          windowWidth = Math.min(windowWidth, contentWidth - remainingMinW[i + 1]);"
        "        }"
        "        windowWidth = Math.min(Math.max(windowWidth, 1), contentWidth - 1);"
        "        zones.push({x: remaining.x, y: remaining.y,"
        "          width: windowWidth, height: remaining.height});"
        "        remaining = {x: remaining.x + windowWidth + innerGap, y: remaining.y,"
        "          width: contentWidth - windowWidth, height: remaining.height};"
        "      } else {"
        "        var contentHeight = remaining.height - innerGap;"
        "        var windowHeight = Math.floor(contentHeight * splitRatio);"
        "        if (minSizes && minSizes.length > 0 && i < minSizes.length"
        "            && minSizes[i].h > 0) {"
        "          windowHeight = Math.max(windowHeight, minSizes[i].h);"
        "        }"
        "        if (minSizes && minSizes.length > 0 && remainingMinH[i + 1] > 0) {"
        "          windowHeight = Math.min(windowHeight,"
        "            contentHeight - remainingMinH[i + 1]);"
        "        }"
        "        windowHeight = Math.min(Math.max(windowHeight, 1), contentHeight - 1);"
        "        zones.push({x: remaining.x, y: remaining.y,"
        "          width: remaining.width, height: windowHeight});"
        "        remaining = {x: remaining.x,"
        "          y: remaining.y + windowHeight + innerGap,"
        "          width: remaining.width, height: contentHeight - windowHeight};"
        "      }"
        "      splitVertical = !splitVertical;"
        "    }"
        "  }"
        "  return zones;"
        "}");
}

} // namespace ScriptedHelpers
} // namespace PlasmaZones
