title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        Before posting, please search existing discussions and issues to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open the editor
        2. Create a zone
        3. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: PlasmaZones Version
      description: Run `plasmazones-editor --version` or check git commit
      placeholder: "1.1.0 or git commit hash"
    validations:
      required: true

  - type: dropdown
    id: display-server
    attributes:
      label: Display Server
      options:
        - Wayland
        - X11
    validations:
      required: true

  - type: input
    id: desktop
    attributes:
      label: Desktop Environment
      description: KDE Plasma version
      placeholder: "Plasma 6.2"
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Distribution
      placeholder: "Arch Linux, Fedora 41, etc."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Check `journalctl --user -u plasmazones` for daemon logs
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Any relevant settings or layout JSON
      render: json

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing discussions and issues
          required: true
        - label: I can reproduce this with default settings
          required: false
