title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature.

        Please search existing discussions first to avoid duplicates or to add to existing conversations.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: A clear description of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this solve or what use case does it enable?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing discussions and issues
          required: true
