// SPDX-FileCopyrightText: 2026 fuddlesworth
// SPDX-License-Identifier: LGPL-2.1-or-later

#include <PhosphorAnimation/PhosphorProfileRegistry.h>
#include <PhosphorAnimation/Profile.h>
#include <PhosphorAnimation/qml/PhosphorMotionAnimation.h>

#include <QGuiApplication>
#include <QQmlComponent>
#include <QQmlEngine>
#include <QQuickItem>
#include <QQuickView>
#include <QQuickWindow>
#include <QSignalSpy>
#include <QTest>
#include <QUrl>

#include <QtPlugin>

// Force-link the static QML module's auto-generated init symbol so the
// test binary registers `org.phosphor.animation` types into the QmlEngine.
// Standard pattern for using a static qt_add_qml_module from a test
// executable — without this, the linker drops the init code as dead
// and `import org.phosphor.animation` fails to resolve.
//
// The qmldir's `classname` field is `org_phosphor_animationPlugin` —
// that's the symbol Q_IMPORT_PLUGIN must reference.
Q_IMPORT_PLUGIN(org_phosphor_animationPlugin)

using namespace PhosphorAnimation;

/**
 * @brief QML Behavior site integration test for PhosphorMotionAnimation.
 *
 * Every other PhosphorMotionAnimation test instantiates the type
 * directly from C++. The production usage site is `Behavior on x {
 * PhosphorMotionAnimation { profile: "..." } }` inside QML — which
 * exercises (a) Qt's Behavior wrapper, (b) the QML metatype
 * registration, (c) the path-string profile binding through the
 * registry, and (d) the inherited QQuickPropertyAnimation animation
 * machinery.
 *
 * A regression in any of those four would pass the unit-level tests
 * and only surface as "this Behavior animation snaps instantly" or
 * "this profile setting has no effect" in interactive use.
 *
 * Software backend chosen for headless CI compatibility (matches the
 * `test_animatedvalue_realwindow.cpp` pattern in this directory).
 */
class TestMotionAnimationBehavior : public QObject
{
    Q_OBJECT

private:
    /// Test-fixture-owned registry — published as the QML default
    /// in initTestCase so QML `profile: "test.fade"` string bindings
    /// resolve through it. Phase A3 of the architecture refactor
    /// retired `PhosphorProfileRegistry::instance()`.
    PhosphorProfileRegistry m_registry;

private Q_SLOTS:

    void initTestCase()
    {
        // Software SG backend so we can run on offscreen QPA without
        // GPU drivers — same rationale as test_animatedvalue_realwindow.cpp.
        QQuickWindow::setSceneGraphBackend(QStringLiteral("software"));

        // Publish the fixture's registry so QML `PhosphorMotionAnimation`
        // resolution (via PhosphorProfileRegistry::defaultRegistry())
        // points at this instance.
        PhosphorProfileRegistry::setDefaultRegistry(&m_registry);

        // Register a deterministic test profile so the QML
        // `profile: "test.fade"` string-binding resolves to known
        // values. Duration is short enough that the test completes
        // quickly but long enough that we can observe an intermediate
        // (not-yet-snapped) value.
        Profile p;
        p.duration = 200.0;
        m_registry.registerProfile(QStringLiteral("test.fade"), p);
    }

    void cleanupTestCase()
    {
        m_registry.clear();
        PhosphorProfileRegistry::setDefaultRegistry(nullptr);
    }

    /// Behavior on x with a PhosphorMotionAnimation child must
    /// interpolate (NOT snap) when the bound property changes. This is
    /// the production usage shape — if Qt's Behavior wrapper, the QML
    /// type registration, or the inherited setEasing path were broken,
    /// the property would jump straight to its target value rather
    /// than easing.
    void testBehaviorInterpolatesPropertyChange()
    {
        QQmlEngine engine;
        // The static QML module's qmldir lives at <build>/qml/org/phosphor/animation/
        // (generated by qt_add_qml_module's OUTPUT_DIRECTORY in qml/CMakeLists.txt).
        // Adding the qml/ root to the import path lets `import
        // org.phosphor.animation 1.0` resolve from a build-tree test
        // without an install step. Mirrors the consumer setup in
        // src/shared/CMakeLists.txt.
        // The static plugin is force-linked via Q_IMPORT_PLUGIN at file
        // scope below — no addImportPath needed; the engine resolves
        // `import org.phosphor.animation` from the linked-in init.

        // Inline QML snippet — parses a tiny scene with one Item that
        // has a Behavior on x using PhosphorMotionAnimation. The
        // initial x is 0; we drive a change to 100 and assert the
        // value is mid-flight (not at 100) shortly after.
        QQmlComponent component(&engine);
        component.setData(R"QML(
import QtQuick 2.15
import org.phosphor.animation 1.0
Item {
    id: root
    width: 100; height: 100
    property real testX: 0
    Behavior on testX {
        PhosphorMotionAnimation { profile: "test.fade" }
    }
}
)QML",
                          QUrl());

        if (component.isError()) {
            QFAIL(qPrintable(QStringLiteral("QML compile failed: ") + component.errorString()));
        }

        QObject* root = component.create();
        QVERIFY(root);

        // Sanity — the property starts at 0.
        QCOMPARE(root->property("testX").toReal(), 0.0);

        // Drive the property change. The Behavior intercepts and
        // routes through the PhosphorMotionAnimation; because the
        // animation has a non-zero duration, the property does NOT
        // snap immediately to 100 — it interpolates.
        root->setProperty("testX", 100.0);

        // Spin the event loop very briefly — long enough for the
        // animation to start ticking but short enough that it cannot
        // have completed (200 ms profile duration; we wait 30 ms
        // which is much less). If the Behavior were broken (no
        // animation, just direct assignment), the value would be
        // 100 immediately. If interpolation works, it's between
        // 0 and 100.
        QTest::qWait(30);
        const qreal mid = root->property("testX").toReal();

        // The interpolated value can be anywhere in (0, 100). Reject
        // the snap-to-target case (==100) and the no-progress case
        // (==0). Both ends would indicate the animation either didn't
        // start or didn't tick.
        QVERIFY2(mid >= 0.0 && mid <= 100.0,
                 qPrintable(QStringLiteral("interpolated value %1 outside [0,100]").arg(mid)));
        QVERIFY2(
            mid < 100.0,
            qPrintable(QStringLiteral("Behavior snapped to target (no interpolation): testX=%1 immediately").arg(mid)));

        // Wait for the animation to settle — the profile duration is
        // 200 ms; 1 second of slack is generous.
        QTRY_COMPARE_WITH_TIMEOUT(root->property("testX").toReal(), 100.0, 1000);

        delete root;
    }

    /// Re-trigger during an in-flight animation. Qt's standard
    /// Behavior semantics is that a new property assignment
    /// "stop-on-set"s the old animation and starts a fresh one
    /// targeting the new value — the in-flight animation is replaced,
    /// not queued. PhosphorMotionAnimation, as a
    /// QQuickPropertyAnimation subclass, inherits that behaviour.
    /// Pin it: the final value is the most-recent target, not the
    /// first.
    void testBehaviorRetriggerStopsAndRestartsAnimation()
    {
        QQmlEngine engine;
        // The static plugin is force-linked via Q_IMPORT_PLUGIN at file
        // scope below — no addImportPath needed; the engine resolves
        // `import org.phosphor.animation` from the linked-in init.
        QQmlComponent component(&engine);
        component.setData(R"QML(
import QtQuick 2.15
import org.phosphor.animation 1.0
Item {
    id: root
    width: 100; height: 100
    property real testX: 0
    Behavior on testX {
        PhosphorMotionAnimation { profile: "test.fade" }
    }
}
)QML",
                          QUrl());
        if (component.isError()) {
            QFAIL(qPrintable(QStringLiteral("QML compile failed: ") + component.errorString()));
        }

        QObject* root = component.create();
        QVERIFY(root);

        // First trigger — start an animation toward 100.
        root->setProperty("testX", 100.0);
        QTest::qWait(30); // partial-flight

        // Re-trigger BEFORE the first animation completes. Qt's
        // Behavior stop-on-set replaces the in-flight animation with
        // a new one targeting the second value (50).
        root->setProperty("testX", 50.0);

        // The settled value MUST be the second target (50), not the
        // first (100). If stop-on-set were broken, the first animation
        // would continue and the value would land at 100.
        QTRY_COMPARE_WITH_TIMEOUT(root->property("testX").toReal(), 50.0, 1000);

        delete root;
    }
};

QTEST_MAIN(TestMotionAnimationBehavior)
#include "test_motionanimation_behavior.moc"
