# PlasmaZones RPM Spec File
# Window tiling and autotiling for KDE Plasma
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Requires Plasma 6.7+ (KF6 6.26, Qt 6.10, KWin 6.7+).
#
# Build: rpmbuild -ba plasmazones.spec
# Clean build: mock -r fedora-43-x86_64 plasmazones-1.2.0-1.fc43.src.rpm
#
# Version and changelog are set by CI from the git tag and CHANGELOG.md.
# Generated by packaging/generate-changelog.sh during CI.
# Do not edit Version or changelog manually — they are overwritten on release.

# SPDX-FileCopyrightText: 2026 fuddlesworth
# SPDX-License-Identifier: GPL-3.0-or-later

Name:           plasmazones
Version:        0.0.0
Release:        1%{?dist}
Summary:        Window tiling and autotiling for KDE Plasma

License:        GPL-3.0-or-later AND LGPL-2.1-or-later
URL:            https://github.com/fuddlesworth/PlasmaZones
Source0:        %{url}/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz

# Plasma 6 / Wayland only
ExclusiveArch:  x86_64 aarch64

# Build tools
# wayland-scanner: protocol-glue code generator, located by CMake via
# find_program (CMakeLists.txt:186, libs/phosphor-wayland/CMakeLists.txt:46).
# Depend on the pkgconfig(wayland-scanner) capability, not the bare
# /usr/bin/wayland-scanner file path: the file-path form is reported
# unresolvable by OBS on openSUSE Tumbleweed. wayland-devel ships both the
# wayland-scanner binary and wayland-scanner.pc on Fedora and openSUSE, so
# the pkgconfig capability resolves everywhere and pulls in the executable.
BuildRequires:  pkgconfig(wayland-scanner)
BuildRequires:  cmake >= 3.16
BuildRequires:  extra-cmake-modules >= 6.26.0
BuildRequires:  gcc-c++
%if 0%{?suse_version}
BuildRequires:  ninja
%else
BuildRequires:  ninja-build
%endif

# Qt6
%if 0%{?suse_version}
BuildRequires:  cmake(Qt6Core) >= 6.10.0
BuildRequires:  cmake(Qt6DBus)
BuildRequires:  cmake(Qt6Gui)
BuildRequires:  cmake(Qt6Qml)
BuildRequires:  cmake(Qt6Quick)
BuildRequires:  cmake(Qt6QuickControls2)
BuildRequires:  cmake(Qt6Widgets)
BuildRequires:  cmake(Qt6Concurrent)
BuildRequires:  cmake(Qt6ShaderTools)
BuildRequires:  cmake(Qt6ShaderToolsPrivate)
BuildRequires:  qt6-svg-devel
BuildRequires:  qt6-core-private-devel
BuildRequires:  qt6-gui-private-devel
# Qt6QuickPrivate (CMakeLists.txt:120). openSUSE ships the private Quick
# CMake config in this explicit package; it does not auto-provide a
# cmake(Qt6QuickPrivate) capability, unlike Qt6ShaderToolsPrivate.
BuildRequires:  qt6-quick-private-devel
BuildRequires:  vulkan-devel
%else
BuildRequires:  qt6-qtbase-devel >= 6.10.0
BuildRequires:  qt6-qtbase-private-devel
BuildRequires:  qt6-qtdeclarative-devel
BuildRequires:  qt6-qttools-devel
BuildRequires:  qt6-qtshadertools-devel
BuildRequires:  qt6-qtsvg-devel
%endif

# KDE Frameworks 6 (6.26+ for Plasma 6.7 API)
%if 0%{?suse_version}
BuildRequires:  cmake(KF6KCMUtils)
BuildRequires:  cmake(KF6GlobalAccel)
BuildRequires:  cmake(KF6Kirigami)
%else
BuildRequires:  kf6-kcmutils-devel >= 6.26.0
BuildRequires:  kf6-kglobalaccel-devel >= 6.26.0
BuildRequires:  kf6-kirigami-devel >= 6.26.0
%endif

# Plasma 6.7 / KWin 6.7 (effect API)
# The KWin effect plugin's IID embeds KWin's exact upstream version
# (KWIN_PLUGIN_VERSION_STRING in /usr/include/kwin/config-kwin.h). KWin refuses
# to load any effect whose IID doesn't match its own version string — even
# across patch releases (e.g. 6.7.0 → 6.7.1). We capture the build-time KWin
# version below and emit an exact Requires so this package fails to install on
# systems with a mismatched KWin instead of installing silently broken.
%if 0%{?suse_version}
BuildRequires:  kwin6-devel
# find_package(KWin) (kwin-effect/CMakeLists.txt:20) pulls in KWinConfig.cmake,
# which find_dependency()s the targets below (see KWinConfig.cmake.in, Plasma
# 6.7). openSUSE's kwin6-devel does not drag these into the build root itself,
# so the KWin effect's CMake configure step fails without them. KF6Config /
# KF6CoreAddons currently arrive transitively, but are listed explicitly so the
# dependency is not silently load-bearing on another package.
BuildRequires:  cmake(KF6Config)
BuildRequires:  cmake(KF6CoreAddons)
BuildRequires:  cmake(KF6WindowSystem)
BuildRequires:  pkgconfig(epoxy)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  cmake(Qt6WaylandClient)
BuildRequires:  cmake(Qt6WaylandClientPrivate)
BuildRequires:  wayland-devel
BuildRequires:  cmake(PlasmaActivities)
BuildRequires:  pkgconfig(systemd)
# systemd-rpm-macros defines %%systemd_user_post / %%systemd_user_postun_*
# — without it those macros expand to empty and the user-unit hooks at
# %%post / %%postun silently no-op on openSUSE. The %% escapes keep rpm
# from expanding the macro names inside this comment: on openSUSE
# %%systemd_user_post expands to a multi-line helper invocation, which
# lands in the preamble as an "Unknown tag" error.
BuildRequires:  systemd-rpm-macros
%else
BuildRequires:  kwin-devel >= 6.7.0
BuildRequires:  qt6-qtwayland-devel
BuildRequires:  libepoxy-devel
BuildRequires:  wayland-devel
BuildRequires:  libdrm-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  vulkan-loader-devel
BuildRequires:  vulkan-headers
BuildRequires:  plasma-activities-devel
BuildRequires:  systemd-rpm-macros
%endif
%{?systemd_requires}

# Build-time KWin upstream version (Fedora). kwin-devel is BuildRequired above,
# so it is installed when this spec is parsed in the rpmbuild chroot. The query
# falls back to a permissive minimum when kwin-devel is absent — notably the
# minimal COPR SRPM-build chroot, where the spec only has to parse.
#
# `rpm -q` prints "package kwin-devel is not installed" to STDOUT (not stderr)
# and exits non-zero when the package is missing, so a bare
# `rpm -q ... || echo 6.7.0` leaves that message in the macro and `echo` adds
# a SECOND line. A multi-line macro then injects a newline into every
# `Requires: kwin = %%{kwin_version}` use, and rpm parses the stray `6.7.0` as
# its own tag ("Unknown tag: 6.7.0"). Capture stdout first and only emit it on
# success so the macro is always a single clean token.
%global kwin_version %(out=$(rpm -q --qf '%%{VERSION}' kwin-devel 2>/dev/null) && echo "$out" || echo 6.7.0)

# Runtime dependencies — RPM auto-generates most from sonames;
# explicit Requires ensure minimum versions on Fedora.
%if !0%{?suse_version}
Requires:       qt6-qtbase >= 6.10.0
Requires:       qt6-qtdeclarative
Requires:       qt6-qtshadertools
Requires:       kf6-kirigami >= 6.26.0
Requires:       kf6-kcmutils >= 6.26.0
Requires:       qt6-qtwayland >= 6.10.0
# Exact KWin patch pin — see note above the BuildRequires block.
Requires:       kwin = %{kwin_version}
%endif
Requires:       hicolor-icon-theme

# Post-install scriptlet dependencies — must be in preamble (rpmbuild
# parses Requires(post) only here; placing them after %%install is
# silently dropped on stricter parsers). hicolor-icon-theme is already
# in Requires above; the post-only entries are the cache-refresh tools.
# Scoped to Fedora because openSUSE provides equivalent functionality
# via %%suse_update_desktop_file and file-triggers, and ships these
# tools under different package names.
%if !0%{?suse_version}
Requires(post): /usr/bin/gtk-update-icon-cache
Requires(post): /usr/bin/update-desktop-database
Requires(post): /usr/bin/update-mime-database
%endif

%description
PlasmaZones is a window tiling and zone management tool for KDE Plasma 6.

Features:
- Drag windows to predefined zones
- Automatic tiling with multiple layout algorithms
- Custom zone layouts with visual editor
- Modifier key activation (Shift, Ctrl, etc.)
- Multi-monitor support
- Keyboard navigation between zones
- Activity and virtual desktop-based layout switching
- Wayland-native using Layer Shell

%prep
%autosetup -n PlasmaZones-%{version}

%build
%cmake \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DBUILD_TESTING=OFF
%cmake_build

%install
%cmake_install

# This package ships PlasmaZones as an end-user application, not a
# Phosphor SDK. Drop the development files the component libraries
# install: public headers, CMake package configs, and the unversioned
# .so devel symlinks. Only the versioned runtime libraries (.so.*) are
# kept. Without this openSUSE's rpmlint fails the build on
# devel-file-in-non-devel-package; there is no -devel subpackage by
# design. Every Phosphor/plasmazones library sets SOVERSION, so the
# bare .so is always a devel symlink and never the runtime object.
rm -rf %{buildroot}%{_includedir}/Phosphor*
rm -rf %{buildroot}%{_libdir}/cmake/Phosphor*
rm -f  %{buildroot}%{_libdir}/libPhosphor*.so
rm -f  %{buildroot}%{_libdir}/libplasmazones*.so

%post
# Register newly installed shared libraries with the dynamic linker.
/sbin/ldconfig
# Refresh KDE service cache
/usr/bin/kbuildsycoca6 --noincremental 2>/dev/null || :
# Update icon / desktop / MIME caches
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
/usr/bin/update-desktop-database -q %{_datadir}/applications &>/dev/null || :
/usr/bin/update-mime-database %{_datadir}/mime &>/dev/null || :
%systemd_user_post plasmazones.service
echo ""
echo "PlasmaZones: the KWin effect is enabled by default, but KWin must"
echo "be restarted to load it. Log out and back in, or run:"
echo "  kwin_wayland --replace &"
echo ""

%preun
%systemd_user_preun plasmazones.service

%postun
/sbin/ldconfig
/usr/bin/kbuildsycoca6 --noincremental 2>/dev/null || :
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
/usr/bin/update-desktop-database -q %{_datadir}/applications &>/dev/null || :
/usr/bin/update-mime-database %{_datadir}/mime &>/dev/null || :
%systemd_user_postun_with_restart plasmazones.service

%files
%license LICENSE
%license COPYING.LESSER
%doc README.md

# Executables — globbed by the plasmazones prefix (plasmazonesd plus
# plasmazones-editor / -report / -settings). phosphor-shell is
# deliberately NOT matched: it is gated behind the BUILD_PHOSPHOR_SHELL
# CMake option (work in progress, default OFF), so packaging builds
# never produce it and listing it explicitly would fail rpmbuild.
%{_bindir}/plasmazones*

# Component libraries — every Phosphor component library plus the
# plasmazones core/rendering libs. Globbed by naming convention: this
# is a single monolithic package, the build installs only this
# project's files, so a new component library needs no spec edit.
# Only the versioned runtime objects (.so.*) are shipped — the
# unversioned .so devel symlinks, public headers and CMake package
# configs are stripped in %%install (this is an end-user application,
# not a Phosphor SDK, and there is no -devel subpackage by design).
# Excludes the QML plugin under qt6/qml/, which the glob below owns.
%{_libdir}/libPhosphor*.so.*
%{_libdir}/libplasmazones*.so.*

# KWin effect plugin. openSUSE: own the parent plugin directories so the
# OBS "directories not owned by a package" check passes — no hard
# dependency drags them in. On Fedora the kwin package owns them.
%if 0%{?suse_version}
%dir %{_libdir}/qt6/plugins/kwin
%dir %{_libdir}/qt6/plugins/kwin/effects
%dir %{_libdir}/qt6/plugins/kwin/effects/plugins
%endif
%{_libdir}/qt6/plugins/kwin/effects/plugins/kwin_effect_plasmazones.so

# Layer-shell QPA plugin (PhosphorWayland)
%{_libdir}/qt6/plugins/wayland-shell-integration/phosphorwayland-qpa.so

# KCM sub-modules (System Settings)
%{_libdir}/qt6/plugins/plasma/kcms/systemsettings/kcm_plasmazones_*.so

# QML modules (PhosphorAnimation and any future org.phosphor module)
%{_libdir}/qt6/qml/org/phosphor/

# D-Bus interfaces
%{_datadir}/dbus-1/interfaces/org.plasmazones.*.xml

# D-Bus session activation file (daemon auto-launch on first bus call)
%{_datadir}/dbus-1/services/org.plasmazones.service

# Desktop files
%{_datadir}/applications/org.plasmazones.*.desktop
%{_datadir}/applications/kcm_plasmazones_*.desktop

# AppStream metainfo for distro app stores (Discover, GNOME Software, ...)
%{_datadir}/metainfo/org.plasmazones.*.metainfo.xml

# KGlobalAccel component (display name + icon in Shortcuts KCM)
%{_datadir}/kglobalaccel/plasmazonesd.desktop

# System Settings category. openSUSE: own the parent directories (same
# OBS unowned-directory check as the KWin effect above); the
# systemsettings package owns them on Fedora.
%if 0%{?suse_version}
%dir %{_datadir}/systemsettings
%dir %{_datadir}/systemsettings/categories
%endif
%{_datadir}/systemsettings/categories/settings-windowmanagement-plasmazones.desktop

# Runtime data — application data plus the bundled Phosphor component
# data trees (phosphor-shell assets, phosphorshaders GLSL,
# phosphorwayland shaders + protocol XMLs).
%{_datadir}/plasmazones/
%{_datadir}/phosphor*/

# Icons — the standard hicolor theme directories are owned by
# hicolor-icon-theme (a hard Requires), so glob only our SVGs there.
# hicolor-light is a PlasmaZones-specific theme variant that no other
# package ships, so own its whole tree — otherwise the OBS
# "directories not owned by a package" check fails.
%{_datadir}/icons/hicolor/scalable/apps/*.svg
%{_datadir}/icons/hicolor-light/

# Systemd user service
%{_userunitdir}/plasmazones.service


%changelog
# Generated from CHANGELOG.md by packaging/generate-changelog.sh during CI.
# Do not edit manually — entries below are overwritten on release.
# Seed entry so `rpmbuild -bs` against this spec without CI tooling
# produces a valid SRPM (the generator script replaces it on release).
* Mon Jan 01 1970 fuddlesworth - 0.0.0-1
- placeholder
