# PlasmaZones RPM Spec File
# Window tiling and autotiling for KDE Plasma
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Requires Plasma 6.6+ (KF6 6.6, Qt 6.6, KWin 6.6+).
#
# Build: rpmbuild -ba plasmazones.spec
# Clean build: mock -r fedora-43-x86_64 plasmazones-1.2.0-1.fc43.src.rpm
#
# Version and changelog are set by CI from the git tag and CHANGELOG.md.
# Generated by packaging/generate-changelog.sh during CI.
# Do not edit Version or changelog manually — they are overwritten on release.

Name:           plasmazones
Version:        0.0.0
Release:        1%{?dist}
Summary:        Window tiling and autotiling for KDE Plasma

License:        GPL-3.0-or-later AND LGPL-2.1-or-later
URL:            https://github.com/fuddlesworth/PlasmaZones
Source0:        %{url}/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz

# Plasma 6 / Wayland only
ExclusiveArch:  x86_64 aarch64

# Build tools
BuildRequires:  /usr/bin/wayland-scanner
BuildRequires:  cmake >= 3.16
BuildRequires:  extra-cmake-modules >= 6.6.0
BuildRequires:  gcc-c++
%if 0%{?suse_version}
BuildRequires:  ninja
%else
BuildRequires:  ninja-build
%endif

# Qt6
%if 0%{?suse_version}
BuildRequires:  cmake(Qt6Core) >= 6.6.0
BuildRequires:  cmake(Qt6DBus)
BuildRequires:  cmake(Qt6Gui)
BuildRequires:  cmake(Qt6Qml)
BuildRequires:  cmake(Qt6Quick)
BuildRequires:  cmake(Qt6QuickControls2)
BuildRequires:  cmake(Qt6Widgets)
BuildRequires:  cmake(Qt6Concurrent)
BuildRequires:  cmake(Qt6ShaderTools)
BuildRequires:  cmake(Qt6ShaderToolsPrivate)
BuildRequires:  qt6-svg-devel
BuildRequires:  qt6-core-private-devel
BuildRequires:  qt6-gui-private-devel
BuildRequires:  vulkan-devel
%else
BuildRequires:  qt6-qtbase-devel >= 6.6.0
BuildRequires:  qt6-qtbase-private-devel
BuildRequires:  qt6-qtdeclarative-devel
BuildRequires:  qt6-qttools-devel
BuildRequires:  qt6-qtshadertools-devel
BuildRequires:  qt6-qtsvg-devel
%endif

# KDE Frameworks 6 (6.6+ for Plasma 6.6 API)
%if 0%{?suse_version}
BuildRequires:  cmake(KF6KCMUtils)
BuildRequires:  cmake(KF6GlobalAccel)
BuildRequires:  cmake(KF6Kirigami)
%else
BuildRequires:  kf6-kcmutils-devel >= 6.6.0
BuildRequires:  kf6-kglobalaccel-devel >= 6.6.0
BuildRequires:  kf6-kirigami-devel >= 6.6.0
%endif

# Plasma 6.6 / KWin 6.6 (effect API)
# The KWin effect plugin links against libkwin; RPM auto-generates soname deps
# for ABI safety. Patch releases (6.6.x) maintain ABI and IID compatibility.
%if 0%{?suse_version}
BuildRequires:  kwin6-devel
BuildRequires:  cmake(Qt6WaylandClient)
BuildRequires:  cmake(Qt6WaylandClientPrivate)
BuildRequires:  wayland-devel
BuildRequires:  cmake(PlasmaActivities)
BuildRequires:  pkgconfig(systemd)
%else
BuildRequires:  kwin-devel >= 6.6.0
BuildRequires:  qt6-qtwayland-devel
BuildRequires:  libepoxy-devel
BuildRequires:  wayland-devel
BuildRequires:  libdrm-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  vulkan-loader-devel
BuildRequires:  vulkan-headers
BuildRequires:  plasma-activities-devel
BuildRequires:  systemd-rpm-macros
%endif
%{?systemd_requires}

# Runtime dependencies — RPM auto-generates most from sonames;
# explicit Requires ensure minimum versions on Fedora.
%if !0%{?suse_version}
Requires:       qt6-qtbase >= 6.6.0
Requires:       qt6-qtdeclarative
Requires:       qt6-qtshadertools
Requires:       kf6-kirigami >= 6.6.0
Requires:       kf6-kcmutils >= 6.6.0
Requires:       qt6-qtwayland >= 6.6.0
Requires:       kwin >= 6.6.0
%endif
Requires:       hicolor-icon-theme

%description
PlasmaZones is a window tiling and zone management tool for KDE Plasma 6.

Features:
- Drag windows to predefined zones
- Automatic tiling with multiple layout algorithms
- Custom zone layouts with visual editor
- Modifier key activation (Shift, Ctrl, etc.)
- Multi-monitor support
- Keyboard navigation between zones
- Activity and virtual desktop-based layout switching
- Wayland-native using Layer Shell

%prep
%autosetup -n PlasmaZones-%{version}

%build
%cmake \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DBUILD_TESTING=OFF
%cmake_build

%install
%cmake_install

%post
# Refresh KDE service cache
/usr/bin/kbuildsycoca6 --noincremental 2>/dev/null || :
# Update icon cache
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
%systemd_user_post plasmazones.service
echo ""
echo "PlasmaZones: the KWin effect is enabled by default, but KWin must"
echo "be restarted to load it. Log out and back in, or run:"
echo "  kwin_wayland --replace &"
echo ""

%preun
%systemd_user_preun plasmazones.service

%postun
/usr/bin/kbuildsycoca6 --noincremental 2>/dev/null || :
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
%systemd_user_postun_with_restart plasmazones.service

%files
%license LICENSE
%license COPYING.LESSER
%doc README.md

# Executables
%{_bindir}/plasmazonesd
%{_bindir}/plasmazones-editor
%{_bindir}/plasmazones-settings
%{_bindir}/plasmazones-report

# Libraries
%{_libdir}/libPhosphorLayoutApi.so*
%{_libdir}/libPhosphorZones.so*
%{_libdir}/libPhosphorIdentity.so*
%{_libdir}/libPhosphorTiles.so*
%{_libdir}/libPhosphorConfig.so*
%{_libdir}/libPhosphorWayland.so*
%{_libdir}/libPhosphorRendering.so*
%{_libdir}/libPhosphorLayer.so*
%{_libdir}/libplasmazones_core.so*
%{_libdir}/libplasmazones_rendering.so*

# KWin effect plugin
%{_libdir}/qt6/plugins/kwin/effects/plugins/kwin_effect_plasmazones.so

# Layer-shell QPA plugin (PhosphorWayland)
%{_libdir}/qt6/plugins/wayland-shell-integration/phosphorwayland-qpa.so

# PhosphorLayoutApi development headers and CMake config
%{_includedir}/PhosphorLayoutApi/
%{_libdir}/cmake/PhosphorLayoutApi/

# PhosphorZones development headers and CMake config
%{_includedir}/PhosphorZones/
%{_libdir}/cmake/PhosphorZones/

# PhosphorIdentity development headers and CMake config
%{_includedir}/PhosphorIdentity/
%{_libdir}/cmake/PhosphorIdentity/

# PhosphorTiles development headers and CMake config
%{_includedir}/PhosphorTiles/
%{_libdir}/cmake/PhosphorTiles/

# PhosphorConfig development headers and CMake config
%{_includedir}/PhosphorConfig/
%{_libdir}/cmake/PhosphorConfig/

# PhosphorWayland development headers, CMake config, and runtime data
# (bundled shaders + wayland protocol XMLs installed to _datadir/phosphorwayland/).
%{_includedir}/PhosphorWayland/
%{_libdir}/cmake/PhosphorWayland/
%{_datadir}/phosphorwayland/

# PhosphorRendering development headers and CMake config
%{_includedir}/PhosphorRendering/
%{_libdir}/cmake/PhosphorRendering/

# PhosphorLayer development headers and CMake config
%{_includedir}/PhosphorLayer/
%{_libdir}/cmake/PhosphorLayer/

# KCM sub-modules (System Settings)
%{_libdir}/qt6/plugins/plasma/kcms/systemsettings/kcm_plasmazones_*.so

# D-Bus interfaces
%{_datadir}/dbus-1/interfaces/org.plasmazones.*.xml

# Desktop files
%{_datadir}/applications/org.plasmazones.editor.desktop
%{_datadir}/applications/org.plasmazones.daemon.desktop
%{_datadir}/applications/org.plasmazones.settings.desktop
%{_datadir}/applications/kcm_plasmazones_*.desktop

# KGlobalAccel component (display name + icon in Shortcuts KCM)
%{_datadir}/kglobalaccel/plasmazonesd.desktop

# System Settings category
%{_datadir}/systemsettings/categories/settings-windowmanagement-plasmazones.desktop

# Data files
%{_datadir}/plasmazones/

# Icons
%{_datadir}/icons/hicolor/scalable/apps/plasmazones.svg
%{_datadir}/icons/hicolor/scalable/apps/plasmazones-editor.svg
%{_datadir}/icons/hicolor/scalable/apps/plasmazones-settings.svg
%{_datadir}/icons/hicolor-light/scalable/apps/plasmazones.svg
%{_datadir}/icons/hicolor-light/scalable/apps/plasmazones-editor.svg
%{_datadir}/icons/hicolor-light/scalable/apps/plasmazones-settings.svg


# Systemd user service
%{_userunitdir}/plasmazones.service

# Snap Assist: env.d config for KWin screenshot auth (system installs use .desktop; this is fallback)
%{_libdir}/environment.d/99-plasmazones-screenshot.conf

%changelog
# Generated from CHANGELOG.md by packaging/generate-changelog.sh during CI.
# Do not edit manually — entries below are overwritten on release.
